[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"
dependencies = [
    "selenium>=4.33.0",
    "telethon>=1.40.0",
    "undetected-chromedriver>=3.5.5",
]
